configure:
  stage: configure_stage
  variables:
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
  script:
    - cd src/nek5000/examples/eddy_uv
    - cmake -DCASENAME=eddy_uv ../../../..
  artifacts:
    paths:
      - src/nek5000/examples/eddy_uv

build_libopenmc:
  stage: build_stage
  dependencies:
    - configure
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 libopenmc

build_libnek5000:
  stage: build_stage
  dependencies:
    - configure
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 libnek5000

build_stream:
  stage: build_stage
  dependencies:
    - build_libopenmc
    - build_libnek5000
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 stream
