stages:
  - config
  - build:modules
  - build:drivers

config:all:
  stage: config
  variables:
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
  script:
    - cd src/nek5000/examples/eddy_uv
    - cmake -DCASENAME=eddy_uv ../../../..
  artifacts:
    paths:
      - src/nek5000/examples/eddy_uv

build:libopenmc:
  stage: build:modules
  dependencies:
    - config:all
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 libopenmc

build:libnek5000:
  stage: build:modules
  dependencies:
    - config:all
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 libnek5000

build:stream:
  stage: build:drivers
  dependencies:
    - build:libopenmc
    - build:libnek5000
  script:
    - cd src/nek5000/examples/eddy_uv
    - make -j -l4 stream
