variables:
  OPENMC_CROSS_SECTIONS: $CI_PROJECT_DIR/endf71_multitemp/cross_sections.xml

stages:
  - setup
  - build_singlerod
  - test_singlerod

download:cross_sections:
  stage: setup
  variables:
    GIT_STRATEGY: clone
  script:
    - wget https://anl.box.com/shared/static/46osfq56h4bd68r6e6pbhupsk4gbnvj2.xz -O - | tar -C $CI_PROJECT_DIR -xvJ

input_patch:nek5000:
  stage: setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd tests/singlerod/short
    - patch -N rodcht.rea ci_config/rodcht_rea.diff || true
    - patch -N SIZE ci_config/SIZE.diff || true

build_singlerod:stream:
  stage: build_singlerod
  dependencies:
    - input_patch:nek5000
  variables:
    GIT_STRATEGY: none
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
  script:
    - mkdir -p tests/singlerod/short/build
    - cd tests/singlerod/short/build
    - cmake -DUSR_LOC=../ ../../../..
    - make -j -l4 stream
    - make -j -l4 test_nek5000_singlerod
    - make -j -l4 test_openmc_singlerod

test_singlerod:nek5000:
  stage: test_singlerod
  dependencies:
    - input_patch:nek5000
    - build_singlerod:stream
  variables:
    GIT_STRATEGY: none
  script:
    - cd tests/singlerod/short/openmc_nek5000
    - if [ -a rodcht.run01.gz ]; then gunzip -f rodcht.run01.gz ; fi
    - mpirun -np 8 ../build/test_nek5000_singlerod

test_singlerod:openmc:
  stage: test_singlerod
  dependencies:
    - download:cross_sections
    - build_singlerod:stream
  variables:
    GIT_STRATEGY: none
    OMP_NUM_THREADS: 4
  script:
    - cd tests/singlerod/short/openmc_nek5000
    - mpirun -np 2 ../build/test_openmc_singlerod

test_singlerod:openmc_nek5000:
  stage: test_singlerod
  dependencies:
    - download:cross_sections
    - input_patch:nek5000
    - build_singlerod:stream
  variables:
    GIT_STRATEGY: none
    OMP_NUM_THREADS: 4
  script:
    - cd tests/singlerod/short/openmc_nek5000
    - if [ -a rodcht.run01.gz ]; then gunzip -f rodcht.run01.gz ; fi
    - mpirun -np 8 ../build/stream

test_singlerod:openmc_heat_surrogate:
  stage: test_singlerod
  dependencies:
    - download:cross_sections
    - build_singlerod:stream
  variables:
    GIT_STRATEGY: none
    OMP_NUM_THREADS: 4
  script:
    - cd tests/singlerod/short/openmc_heat_surrogate
    - mpirun -np 2 ../build/stream
