test:openmc_api:
  stage: test
  variables:
    GIT_STRATEGY: clone
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
  script:
    - cd tests/openmc_api
    - cmake -DCASENAME=ethier ../../
    - make -j -l4 test_openmc_api
    - mpirun -np 4 ./test_openmc_api
