stages:
  - download
  - test

download:cross_sections:
  stage: download
  variables:
    GIT_STRATEGY: clone
  script:
    - wget https://anl.box.com/shared/static/a6sw2cep34wlz6b9i9jwiotaqoayxcxt.xz -O - | tar -C $CI_PROJECT_DIR -xvJ

test:openmc_api:
  stage: test
  dependencies:
    - download:cross_sections
  variables:
    GIT_STRATEGY: none
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
    OPENMC_CROSS_SECTIONS: $CI_PROJECT_DIR/nndc_hdf5/cross_sections.xml
    OMP_NUM_THREADS: 4
  script:
    - cd tests/api_tests
    - cmake -DCASENAME=ethier ../../
    - make -j -l4 test_openmc_api
    - mpirun -np 2 ./test_openmc_api

test:nek5000_api:
  stage: test
  variables:
    GIT_STRATEGY: none
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
  script:
    - cd tests/api_tests
    - cmake -DCASENAME=ethier ../../
    - make -j -l4 test_nek5000_api
    - mpirun -np 8 ./test_nek5000_api

test:coupled_driver:
  stage: test
  dependencies:
    - download:cross_sections
  variables:
    GIT_STRATEGY: none
    CC: mpicc
    CXX: mpicxx
    FC: mpif90
    OPENMC_CROSS_SECTIONS: $CI_PROJECT_DIR/nndc_hdf5/cross_sections.xml
    OMP_NUM_THREADS: 4
  script:
    - cd tests/api_tests
    - cmake -DCASENAME=ethier ../../
    - make -j -l4 test_coupled_api
    - mpirun -np 8 ./test_coupled_api
